// <auto-generated />
namespace TreatTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:TreatTracker.Data/Migrations/202008061933473_Initial.Designer.cs
            get { return "202008061933473_Initial"; }
=======
            get { return "202008061747526_Initial"; }
>>>>>>> c5c8e94085032920d69f9678a93ff5b90467fc65:TreatTracker.Data/Migrations/202008061747526_Initial.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
